version: '3.9'


services:
  database_freelance_calculator:
    image: postgres
    container_name: database_freelance_calculator
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=database_freelance_calculator
    volumes:
      - pgdata:/data/postgres
    
  app:
    build: .
    container_name: freelance-calculator
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database_freelance_calculator
    depends_on:
      - database_freelance_calculator

volumes:
  pgdata:
    driver: local